apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubently-agent
  namespace: kubently-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubently-agent
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubently-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubently-agent
subjects:
- kind: ServiceAccount
  name: kubently-agent
  namespace: kubently-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubently-agent
  namespace: kubently-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubently-agent
  template:
    metadata:
      labels:
        app: kubently-agent
    spec:
      serviceAccountName: kubently-agent
      containers:
      - name: agent
        image: kubently-agent:latest
        imagePullPolicy: Never
        env:
        - name: KUBENTLY_API_URL
          value: "http://172.19.0.2:30080"
        - name: CLUSTER_ID
          valueFrom:
            secretKeyRef:
              name: kubently-agent-secret
              key: CLUSTER_ID
        - name: KUBENTLY_TOKEN
          valueFrom:
            secretKeyRef:
              name: kubently-agent-secret
              key: KUBENTLY_TOKEN
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
