{{- if and .Values.tls.enabled (ne .Values.tls.mode "none") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubently-api-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: kubently-api-tls
  {{- if eq .Values.tls.mode "internal" }}
  # Internal self-signed certificate
  duration: {{ .Values.tls.internal.duration | default "8760h" }}
  renewBefore: {{ .Values.tls.internal.renewBefore | default "720h" }}
  dnsNames:
    - {{ .Values.tls.internal.serviceName }}
    - {{ include "kubently.fullname" . }}-api
    - {{ include "kubently.fullname" . }}-api.{{ .Release.Namespace }}
    - {{ include "kubently.fullname" . }}-api.{{ .Release.Namespace }}.svc
    - {{ include "kubently.fullname" . }}-api.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ include "kubently.fullname" . }}-ca-issuer
    kind: Issuer
  {{- else if eq .Values.tls.mode "external" }}
  # External public certificate
  duration: {{ .Values.tls.external.duration | default "2160h" }}
  renewBefore: {{ .Values.tls.external.renewBefore | default "720h" }}
  dnsNames:
    - {{ required "tls.external.domain must be set for external mode" .Values.tls.external.domain }}
  issuerRef:
    name: {{ .Values.tls.external.issuer }}
    kind: ClusterIssuer
  {{- end }}
{{- end }}