{{- if .Values.api.apiKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubently.fullname" . }}-api-keys
  labels:
    {{- include "kubently.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
data:
  keys: {{ join "," .Values.api.apiKeys | b64enc | quote }}
{{- end }}
{{- if .Values.agent }}
{{- if .Values.agent.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubently.fullname" . }}-agent-token
  labels:
    {{- include "kubently.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
type: Opaque
data:
  {{- if .Values.agent.token }}
  token: {{ .Values.agent.token | b64enc | quote }}
  {{- else }}
  token: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}