apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubently-api
  namespace: kubently
  labels:
    app: kubently-api
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubently-api
  template:
    metadata:
      labels:
        app: kubently-api
        component: api
    spec:
      containers:
      - name: api
        image: kubently/api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: REDIS_URL
          value: "redis://kubently-redis-master:6379"
        - name: REDIS_HOST
          value: "kubently-redis-master"
        - name: API_KEYS
          valueFrom:
            secretKeyRef:
              name: kubently-api-keys
              key: keys
        - name: AGENT_TOKEN_KUBENTLY
          valueFrom:
            secretKeyRef:
              name: kubently-agent-token
              key: token
        - name: LOG_LEVEL
          value: "INFO"
        - name: A2A_EXTERNAL_URL
          value: "http://localhost:8080/a2a/"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3