# Production GKE Values for Kubently
# Captured from: helm get values kubently -n kubently
# Enhanced with: LangSmith tracing support

api:
  # Use existing secret for API keys (prevents Helm from overwriting)
  existingSecret: "kubently-api-keys"

  env:
    A2A_ENABLED: "true"
    A2A_EXTERNAL_URL: https://test-api.kubently.io/a2a/
    A2A_SERVER_DEBUG: "false"
    ANTHROPIC_MODEL_NAME: claude-sonnet-4-20250514
    KUBENTLY_API_URL: http://kubently-api:8080
    LLM_PROVIDER: anthropic-claude
    LOG_LEVEL: INFO
    PORT: "8080"

    # LangSmith Tracing (Production Observability)
    LANGSMITH_TRACING: "true"
    LANGSMITH_PROJECT: "kubently-gke-production"
    LANGSMITH_ENDPOINT: "https://api.smith.langchain.com"
    # LANGSMITH_API_KEY is managed via kubently-llm-secrets secret

  image:
    pullPolicy: Always
    repository: ghcr.io/kubently/kubently
    tag: sha-d9e56ab  # Built with langsmith support

  replicaCount: 2

  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi

  service:
    port: 8080
    targetPort: 8080
    type: ClusterIP

executor:
  clusterId: gke
  enabled: true

  env:
    LOG_LEVEL: INFO

  existingSecret: kubently-executor-token

  image:
    pullPolicy: Always
    repository: ghcr.io/adickinson72/kubently/executor
    tag: 484034a  # Executor doesn't need rebuild (API-only change)

  replicaCount: 1

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

imagePullSecrets:
  - name: ghcr-pull-secret

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  className: nginx
  enabled: false
  hosts:
    - host: test-api.kubently.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - test-api.kubently.io
      secretName: kubently-api-tls

podDisruptionBudget:
  enabled: true
  minAvailable: 1

podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

redis:
  architecture: standalone
  auth:
    enabled: true
  enabled: true
  master:
    persistence:
      enabled: true
      size: 2Gi

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

serviceAccount:
  create: true
  name: kubently

tls:
  enabled: true
  external:
    domain: test-api.kubently.io
    duration: 2160h
    issuer: letsencrypt-prod
    renewBefore: 720h
  mode: external
